version: "3.6"

services:
  docker-textconverter:
    hostname: web-app
    user: root
    command: '/bin/sh -c "$(which supervisord) -c /etc/supervisor/conf.d/supervisord.conf"'
    build:
      context: .
    env_file: '.env'
    ports:
    - 3000:3000
    - 80:80
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
