version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "15000:80"
      - "15001:22"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: manager
      DB_PASS: s3crur3_password123
      DB_NAME: event_management

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: s3crur3_password123
      MYSQL_DATABASE: event_management
      MYSQL_USER: manager
      MYSQL_PASSWORD: s3crur3_password123
