version: '3'

services:
  broken_back_db:
    image: mysql:8.0
    container_name: broken_back_db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
      - broken_back-dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - broken_back-network

  broken_back_wordpress:
    depends_on:
      - broken_back_db
    image: wordpress:5.1.1-fpm-alpine
    container_name: broken_back_wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=broken_back_db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ./html:/var/www/html:rw
      - ./backup.zip:/var/www/html/backup.zip
    #command: bash -c "chmod -r +w /var/www/html"
    networks:
      - broken_back-network

  broken_back_webserver:
    depends_on:
      - broken_back_wordpress
    image: nginx
    container_name: broken_back_webserver
    restart: unless-stopped
    ports:
      - "6083:80"
    volumes:
      - ./html:/var/www/html:rw
      - ./flag.txt:/etc/flag.txt
      - ./backup.zip:/var/www/html/backup.zip
      - ./nginx-conf:/etc/nginx/conf.d

    #command: bash -c "chmod -r +w /var/www/html"

    networks:
      - broken_back-network

volumes:
  broken_back-dbdata:

networks:
  broken_back-network:
    driver: bridge
