#https://github.com/BlueTeamSteve/CVE-2021-41773
version: '3'
services:
  bober_landing:
    image: blueteamsteve/cve-2021-41773:with-cgid
    container_name: bober_landing
    volumes:
      - ./flag.txt:/root/flag.txt
      - ./index.html:/usr/local/apache2/htdocs/index.html
      - ./bober1.png:/usr/local/apache2/htdocs/bober1.png
      - ./bober2.png:/usr/local/apache2/htdocs/bober2.png
      - ./bober3.png:/usr/local/apache2/htdocs/bober3.png
    ports:
      - 6089:80
